#!/bin/sh
echo "Password for default ec2-user: "
read -r password
mkdir -p seedconfig

cat > meta-data <<EOF
local-hostname: vm_hostname
# eth0 is the default network interface enabled in the image. You can configure static network settings with an entry like the following.
network-interfaces: |
  auto eth0
  iface eth0 inet static
  address 192.168.1.10
  network 192.168.1.0
  netmask 255.255.255.0
  broadcast 192.168.1.255
  gateway 192.168.1.254
EOF

cat > user-data << EOF
#cloud-config
#vim:syntax=yaml
users:
# A user by the name ec2-user is created in the image by default.
  - default
chpasswd:
  list: |
    ec2-user:$password
# In the above line, do not add any spaces after 'ec2-user:'.
EOF

genisoimage -output seed.iso -volid cidata -joliet -rock user-data meta-data
